---
title: "DETEKSI SPAM EMAIL"
author: "Miftahul Huda"
date: "2023-05-10"
output: html_document
---

# Library

```{r}
library(dplyr)
library(skimr)
library(DataExplorer)
library(ggplot2)
library(stringr)
library(e1071)
library(tidyverse)
library(ROCR)
```

# Dataset

```{r}
data <- read.csv("https://raw.githubusercontent.com/Mif212/dokumen/main/spam.csv")
glimpse(data)
```

## Seleksi dan Mengubah Nama Kolom

```{r}
data <- select(data, "v1", "v2")
colnames(data) <- c("label", "pesan")
glimpse(data)
```

```{r}
colnames(data)
dim(data)
```

# Data Wrangling

## Cek Missing Value

```{r}
plot_intro(data = data,
           geom_label_args = list(size=2.5))
```

```{r}
skim_without_charts(data)
```

```{r}
sum(is.na(data))
```

## Menghapus Karakter Aneh

```{r}
data$pesan <- gsub("[^a-zA-Z0-9 ]", "", data$pesan)
head(data)
```

# **Eksplorasi Data Analisis**

## Ringkasan Data

```{r}
summary(data)
```

## Frekuensi Label

```{r}
ggplot(data, aes(x = label, fill = label)) +
  geom_bar() + theme_classic() +
  labs(title = "Jumlah Email Spam vs Non-Spam",
       x = "Tipe Email",
       y = "Jumlah")
```

```{r}
table(data$label)
```

## Oversampling

```{r}
index_spam <- which((data$label == "spam") == TRUE)
over_spam <- data[index_spam, ]
data <- rbind(data, over_spam)
dim(data)
```

```{r}
ggplot(data, aes(x = label, fill = label)) +
  geom_bar() + theme_classic() +
  labs(title = "Jumlah Email Spam vs Non-Spam",
       x = "Tipe Email",
       y = "Jumlah")
```

```{r}
table(data$label)
```

## Kata dalam Pesan

```{r}
count_words <- function(text) {
  words <- str_split(text, "\\s+")
  return(length(words[[1]]))
}

data$word_count <- sapply(data$pesan, count_words)

ggplot(data, aes(word_count)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  labs(x = "Value", y = "Frekuensi", title = "Distribusi Jumlah Kata dalam Email") +
  theme_minimal()
```

```{r}
spam_count <- data[which((data$label == "spam") == TRUE),]
ham_count <- data[which((data$label == "ham") == TRUE),]

ggplot(spam_count, aes(word_count)) +
  geom_histogram(binwidth = 1, fill = "red", color = "black") +
  labs(x = "Value", y = "Frekuensi", title = "Distribusi Jumlah Kata dalam Email Spam") +
  theme_minimal()

ggplot(ham_count, aes(word_count)) +
  geom_histogram(binwidth = 1, fill = "green", color = "black") +
  labs(x = "Value", y = "Frekuensi", title = "Distribusi Jumlah Kata dalam Email Ham") +
  theme_minimal()
```

```{r}
spam_mean <- mean(spam_count$word_count)
ham_mean <- mean(ham_count$word_count)
df <- data.frame(
  Category = c("Spam", "Ham"),
  Mean = c(spam_mean, ham_mean)
)
plot <- ggplot(df, aes(x = Category, y = Mean, fill = Category)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  labs(x = "Category", y = "Mean Word Count", title = "Rata-Rata Jumlah Kata") +
  theme_minimal()
print(plot)
```

## Angka dalam Pesan

```{r}
data$number_count <- sapply(strsplit(data$pesan, "\\s+"), function(words) sum(grepl("[0-9]", words)))

ggplot(data, aes(number_count)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  labs(x = "Value", y = "Frekuensi", title = "Distribusi Jumlah Angka dalam Email") +
  theme_minimal()
```

```{r}
spam_count_a <- data[which((data$label == "spam") == TRUE),]
ham_count_a <- data[which((data$label == "ham") == TRUE),]

ggplot(spam_count_a, aes(number_count)) +
  geom_histogram(binwidth = 1, fill = "red", color = "black") +
  labs(x = "Value", y = "Frekuensi", title = "Distribusi Jumlah Angka dalam Email Spam") +
  theme_minimal()

ggplot(ham_count_a, aes(number_count)) +
  geom_histogram(binwidth = 1, fill = "green", color = "black") +
  labs(x = "Value", y = "Frekuensi", title = "Distribusi Jumlah Angka dalam Email Ham") +
  theme_minimal()
```

```{r}
spam_mean_a <- mean(spam_count_a$number_count)
ham_mean_a <- mean(ham_count_a$number_count)
df <- data.frame(
  Category = c("Spam", "Ham"),
  Mean = c(spam_mean_a, ham_mean_a)
)
plot <- ggplot(df, aes(x = Category, y = Mean, fill = Category)) +
  geom_bar(stat = "identity", width = 0.5, color = "black") +
  labs(x = "Category", y = "Mean Word Count", title = "Rata-Rata Jumlah Angka") +
  theme_minimal()
print(plot)
spam_mean_a
ham_mean_a
```

# Naive Bayes

## Split Data

```{r}
set.seed(125)
trainid <- sample(1:nrow(data), nrow(data)*0.8)
training <- data[trainid,]
testing <- data[-trainid,]
```

## Mencari Parameter Terbaik (laplace dan threshold)

```{r}
laplace_values <- c(0, 0.5, 1)
thresholds_values <- c(0.3, 0.5, 0.7)

best_accuracy <- 0
best_laplace <- 0
best_threshold <- 0

for (laplace in laplace_values) {
  for (threshold in thresholds_values) {
    model <- naiveBayes(label ~ ., data = training, laplace = laplace)
    predict <- predict(model, testing, threshold = threshold)
    confusion_matrix <- table(predict, testing$label)
    accuracy <- mean(predict == testing$label)
    if (accuracy > best_accuracy) {
      best_accuracy <- accuracy
      best_laplace <- laplace
      best_threshold <- threshold
    }
  }
}

print(paste("Laplace:", best_laplace))
print(paste("Threshold:", best_threshold))
print(paste("Akurasi:", best_accuracy))
```

## Fit Model

```{r}
model <- naiveBayes(label ~ ., data = training, laplace = best_laplace)
str(model)
predictions <- predict(model, testing, threshold = best_threshold)
```

## Evaluasi Model

```{r}
confusion_matrix <- table(predictions, testing$label)
confusion_matrix
```

```{r}
precision <- confusion_matrix[2, 2] / sum(confusion_matrix[, 2])
print(paste("Presisi:", precision))
```

```{r}
specificity <- confusion_matrix[1, 1] / sum(confusion_matrix[, 1])
print(paste("Spesifisitas:", specificity))
```

```{r}
accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)
print(paste("Akurasi:", accuracy))
```

```{r}
recall <- confusion_matrix[2, 2] / sum(confusion_matrix[2, ])
print(paste("Recall:", recall))
```

```{r}
f1_score <- 2 * (precision * recall) / (precision + recall)
print(paste("F1-Score:", f1_score))
```

## Hasil Prediksi

```{r}
akurasi <- round(accuracy * 100)
error <- round(100 - akurasi)
plot_data <- data.frame(Category = c("Berhasil", "Gagal"), Percentage = c(akurasi, error))

ggplot(plot_data, aes(x = "", y = Percentage, fill = Category)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  geom_text(aes(label = paste0(Percentage, "%")), position = position_stack(vjust = 0.5)) +
  labs(title = "Persentase Keberhasilan Deteksi",
       fill = "Label",
       x = NULL,
       y = NULL) +
  theme_void() +
  theme(legend.position = "bottom") 
```

```{r}
spam_detected <- confusion_matrix["spam", "spam"]
total_spam <- sum(testing$label == "spam")
percentage_detected <- spam_detected / total_spam * 100
plot_data <- data.frame(Label = c("Detected", "Undetected"), 
                        Percentage = c(percentage_detected, 100 - percentage_detected))
p <- ggplot(plot_data, aes(x = "", y = Percentage, fill = Label)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0) +
  labs(title = "Persentase Spam yang Berhasil Terdeteksi",
       x = NULL,
       y = NULL) +
  theme_void() +
  theme(legend.position = "bottom")
p + geom_text(aes(label = paste0(round(Percentage, 2), "%")), position = position_stack(vjust = 0.5))
```

```{r}
ham_detected <- confusion_matrix["ham", "ham"]
total_ham <- sum(testing$label == "ham")
percentage_detected <- ham_detected / total_ham * 100
plot_data <- data.frame(Label = c("Detected", "Undetected"), 
                        Percentage = c(percentage_detected, 100 - percentage_detected))
p <- ggplot(plot_data, aes(x = "", y = Percentage, fill = Label)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0) +
  labs(title = "Persentase Bukan Spam yang Berhasil Terdeteksi",
       x = NULL,
       y = NULL) +
  theme_void() +
  theme(legend.position = "bottom")
p + geom_text(aes(label = paste0(round(Percentage), "%")), position = position_stack(vjust = 0.5))
```
